DROP TABLE IF EXISTS `Post`;
CREATE TABLE `Post` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL,
	`body` LONGTEXT NOT NULL,
	`published` TINYINT(1) NOT NULL DEFAULT 0,
	`date_posted` DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `Comment`;
CREATE TABLE `Comment` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`post_id` INT UNSIGNED NOT NULL REFERENCES `Post`(`id`) ON DELETE CASCADE,
	`username` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`body` LONGTEXT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `Tag`;
CREATE TABLE `Tag` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(128) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PostTag`;
CREATE TABLE `PostTag` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`tag_id` INT UNSIGNED NOT NULL REFERENCES `Tag`(`id`) ON DELETE CASCADE,
	`post_id` INT UNSIGNED NOT NULL REFERENCES `Post`(`id`) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
